### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AgentLeone** [DedInc/byerecaptcha#12]
Able to solve some captchas, but some captchas get this error.....Need some help. Thanks in advance!

Traceback (most recent call last):
  File "C:\Users\Prakashraj\PycharmProjects\pythonProject1\venv\lib\site-packages\byerecaptcha\byerecaptcha.py", line 182, in checkDetection
    descriptionElement = driver.execute_script('return document.getElementsByTagName("strong")[0].textContent')
  File "C:\Users\Prakashraj\PycharmProjects\pythonProject1\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 500, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\Prakashraj\PycharmProjects\pythonProject1\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Prakashraj\PycharmProjects\pythonProject1\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of undefined (reading 'textContent')
  (Session info: MicrosoftEdge=111.0.1661.62)

**Comment by AgentLeone** [comment]
Firefox works fine with no error. Only chrome and edge gets this error
